<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>27854490-1e2e-419e-b7f7-4139bfcf44d4</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..</DockerfileContext>
      <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)</OpenApiDocumentsDirectory>
      <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**" />
    <Compile Remove="Core\1TempNs\**" />
    <Compile Remove="Core\ApiKeys\Application\Queries\**" />
    <Content Remove="Controllers\**" />
    <Content Remove="Core\1TempNs\**" />
    <Content Remove="Core\ApiKeys\Application\Queries\**" />
    <EmbeddedResource Remove="Controllers\**" />
    <EmbeddedResource Remove="Core\1TempNs\**" />
    <EmbeddedResource Remove="Core\ApiKeys\Application\Queries\**" />
    <None Remove="Controllers\**" />
    <None Remove="Core\1TempNs\**" />
    <None Remove="Core\ApiKeys\Application\Queries\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Core\TagNs\Application\Commands\CreateTagCommandHandler.cs.ignore" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.0.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.12.1" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
    <!--<PackageReference Include="Mapster.EFCore" Version="5.1.1" />-->
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1-Preview.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.5.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.1" />
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ContentHandler\ContentHandler.csproj" />
  </ItemGroup>

  
      
      
      
      
      
      
      
    
    
    
    
    
    <ItemGroup>
    <Folder Include="Core\ArticleNs\Application\Handlers\" />
  </ItemGroup>

</Project>
