upstream minicc_web_upstream {
    server minicc-web:3000;
    keepalive 16;
}

upstream minicc_api_upstream {
    server minicc-api:8080;
    keepalive 16;
}

upstream image_proxy_upstream {
    server image-proxy:8080;
    keepalive 16;
}

server {
    listen 80;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;

    # 转发 "/"
    location = / {
        proxy_pass http://minicc_web_upstream;
    }

    # 转发 "/imageProxy"
    location /imageProxy {
        rewrite ^/imageProxy/(.*)$ /$1 break;
        proxy_pass http://image_proxy_upstream;
    }

    # 转发 "/pages/*"
    location /pages/ {
        proxy_pass http://minicc_web_upstream;
    }

    # "/_next/*"（Next.js 静态资源）
    location /_next/ {
        proxy_pass http://minicc_web_upstream;
    }
    

    # 转发 "/api/*"
    location /api/ {
        proxy_pass http://minicc_api_upstream;
    }
}
